---
title: "2023_DAIE_GCA_ZW_LC"
author: "Mark (Zak) White & Lee Cunningham"
date: "19th November, 2018"
output: html_notebook
//toc: true
---

# Install from CRAN (Installing Tidyverse)
install.packages("tidyverse")

library("tidyverse")
require("tidyverse")
# Cleaning the data
<!-- Control <- read.csv("D:\\Games Dev\\Data-Analytics-group-CA-MW-LC\\GROUP_2_2023_GCA_RESULTS_CONTROL.csv") -->
<!-- Experimental <- read.csv("D:\\Games Dev\\Data-Analytics-group-CA-MW-LC\\GROUP_2_2023_GCA_RESULTS_EXPERIMENTAL.csv") -->

Control <- read.csv("C:\Users\leecu\Desktop\MScY1\Data Analytics\Data-Analytics-group-CA-MW-LC/GROUP_2_2023_GCA_RESULTS_CONTROL.csv")
Experimental <- read.csv("C:\Users\leecu\Desktop\MScY1\Data Analytics\Data-Analytics-group-CA-MW-LC/GROUP_2_2023_GCA_RESULTS_EXPERIMENTAL.csv")

View(Experimental)
glimpse(Experimental)
unique(Control$gender)
unique(Experimental$gender)

#replacing the F in the control group to female as it is a safe assumption
Control$gender[Control$gender== "F"] <- "female"
Control
view(Control)
#Replacing the "Male" with male in Experimental
Experimental$gender[Experimental$gender== "Male"] <- "male"
View(Experimental)
unique(Control$gender)
unique(Experimental$gender)

#getting some mean data from variables
mean(Control$pretrial_GAD)
mean(Experimental$pretrial_GAD)
mean(Control$posttrial_GAD)
mean(Experimental$posttrial_GAD)

##searching for incomplete data Reference https://www.youtube.com/watch?v=sV5lwAJ7vnQ 17:05
Control %>%
  select(patientID, gender, pretrial_GAD, pretrial_STAI, posttrial_GAD, posttrial_STAI) %>%
  filter(!complete.cases(.))
  
Experimental %>%
  select(patientID, gender, pretrial_GAD, pretrial_STAI, posttrial_GAD, posttrial_STAI) %>%
  filter(!complete.cases(.))


#This is the R way of finding duplicates
Control[duplicated(Control), ]
Experimental[duplicated(Experimental), ]

#This is the tidyverse way of finding distinct entries Reference: https://www.youtube.com/watch?v=sV5lwAJ7vnQ 25:00
Control %>%
  distinct()

Experimental %>%
  distinct()
  
# Checking for Outliers)
* Pre-Trial GAD - Control
boxplot(Control$pretrial_GAD)
plot(Control$pretrial_GAD)
* There are no outliers in the Control pretrial_GAD data set

* Post-Trial GAD - Control
boxplot(Control$posttrial_GAD)
*One outlier in the data
for (i in 1:ncol(Control$posttrial_GAD)) 
{
if (sum(boxplot.stats(Control$posttrial_GAD[[i]]$out) > 0) 
{
 <!-- # Calculate Lower & Upper Range  -->
q1 <- quantile(Control$posttrial_GAD[[i]], 0.30)
q3 <- quantile(Control$postrial_GAD[[i]], 0.75)
iqr <- q3 - q1
upper_limit <- q3 + 1.5 * iqr
lower_limit <- q1 - 1.5 * iqr
<!-- # Removes Outliers -->
Control$posttrial_GAD <- %>%
filter(Control$posttrial_GAD[[i]] >= lower_limit & Control$posttrial_GAD[[i]] <= upper_limit)
}
}
<!-- # Reference https://www.youtube.com/watch?v=d7OYxxbcGS4 -->

boxplot(Control$posttrial_GAD)

* Pre-trial STAI - Control
boxplot(Control$pretrial_STAI)
<!-- plot(Control$pretrial_STAI) -->
* There are no outliers in the Control pretrial_GAD data set

* Post-Trial STAI - Control
boxplot(Control$posttrial_STAI)
* One outlier in data
//remove outlier------------------------------------------------------------------------------------

* Pre-trial GAD - Experimental
boxplot(Experimental$pretrial_GAD)
*There are no outliers in the Experimental pretrial_GAD data set

* Post-Trial GAD - Experimental
boxplot(Experimental$posttrial_GAD)
*There are no outliers in the Experimental posttrial_GAD data set

* Pre-trial STAI - Experimental
boxplot(Experimental$pretrial_STAI)
*There are no outliers in the Experimental pretrial_STAI data set

* Post-Trial STAI - Experimental
boxplot(Experimental$posttrial_STAI)
x <- Experimental$posttrial_STAI

<!-- Detect Outlier Function -->
detect_outlier <- function(x){
Quantile1 <- quantile(x, probs=.25)
Quantile3 <- quantile(x, probs=.75)
IQR = Quantile3 - Quantile1
x > Quantile3 + (IQR * 1.5) | x < Quantile1 - (IQR * 1.5)
}

<!-- Remove Outlier Function -->
remove_outlier <- function(Experimental, columns = names(Experimental)){
for (col in columns) {
Experimental <- Experimental[idetect_outlier(Experimental[[col]]), ]
}
print("Remove outliers")
}

<!-- Reference: https://www.geeksforgeeks.org/how-to-remove-outliers-from-multiple-columns-in-r-dataframe/ -->

### **Abstract**

##### **Aim and Rationale**
##### **Participants and Setting**
##### **Experiment Design**
##### **Results Gathering**
##### **Findings/ Implications**

### **Introduction**

##### **Topic and Context**
##### **Rationale**
##### **Hypothesis**

### **Method**

##### **Participants**
##### **Design**
##### **Materials**
##### **Procedure**

### **Results**

##### **Descriptive Statistics**
##### **Inferential Statistics**
##### **Statistical Tests**
##### **Magnitude and Direction of Results**

### **Discussion**

##### **Outline Findings and Relation To The Hypothesis**
##### **Limitations (if confounding variables are clearly identified by your group)**

### **References**

## ---------------------------------------------------------------------------------------------

### **Abstract** (2.5M)
##### **Aim and Rationale**
* The aim of the experiment was to find whether the use of VR-based therapy would have a positive effect on patients who are undergoing treatment for Generalized Anxiety Disorder (GAD).
* Virtual Reality offers immersive experiences that have the ability to simulate real-world scenarios in a controlled environment. VR allows for desensitization to certain scenarios by exposing patients to situations that can trigger anxiety. 
Post-Traumatic Stress Disorder, Acrophobia and Social Anxiety Disorders can be treated through the use of VR exposure therapy (VRET). The integration of VR into therapy practices, showcases the potential it has to make positive changes to treatments for anxiety disorder.
            
##### **Participants and Setting**
* There was **180** participants in total for this study. They were **randomly sampled** from the clinic's client list. **96 were Male** and **84 were Female**. They were randomly assigned into the two groups.
* **Control (Traditional CBT, no VR) (M = 48, F = 42)**
* **Experimental (VR-Based Therapy) (M = 48, F = 42)**
* All participants were between the ago of **18-40** years old.

##### **Experiment Design**
* The two groups proceeded to go to 12 weeks of treatment with a therapist in 50 minute sessions. During the treatment sessions, the patients either experienced the traditional CBT or underwent the VR-Based therapy.

##### **Results Gathering**
* In this study, the participants were asked to self-report the severity of the anxiety they were feeling. The measurements used were the 'State-Trait Anxiety Inventory' and 'Generalised Anxiety Disorder 7 Item Scale'. Both use a range of 0 - 10.

##### **Findings/ Implications**
* FILL THIS OUT - LEE

### 4 - **Introduction** (15M)
##### **Topic and Context**
* The amount of people who suffer from anxiety disorders worldwide is approximately 301 million, World Health Organisation, 2019.
* Anxiety disorders are mental disorders which can include a variety of feelings such as anxiety and fear. These feelings can cause individuals to experience a 'racing heart' and/ or 'shaky limbs'. Typically, anxiety is a response to stress but individuals who suffer from anxiety disorders tend to feel these unwanted emotions all the time. This can seriously affect their performance in physical activities, work, school or friendships.
* Triggers for these anxiety disorders can stem from wide range of factors such as medical conditions, the surrounding environment and genetics. There are many different types of anxiety disorders. These include Generalized Anxiety Disorder, Social Anxiety Disorders, Panic Disorders, Separation Anxiety Disorder and Agoraphobia. There are many treatment options available for anxiety disorders including medication, behavior therapy and psychotherapy.


##### **Rationale**
* The treatment of anxiety disorders is being transformed by Virtual Reality as it can simulate real-world scenarios in a controlled environment that can be immerse and therapeutic to individuals with anxiety disorders. VR exposure therapy allows individuals to be exposed to situations that can trigger their anxiety. Through consistent sessions the individual can be desensitized to these triggers which can allow traditional cognitive-behavioral therapy. The integration of Virtual Reality into therapeutic practices shows that it has the potential to positively change the treatments for anxiety disorders.

##### **Hypothesis**
* Is traditional Cognitive Behavioral Therapy (CBT) more effective
than Vr-Based therapy?
  H0 : μ1 = μ2 or μ1 - μ2 = 0.
  Ha : μ1 > μ2 or μ1 − μ2 > 0.


### 5 - **Method** (20M)
##### **Participants**
* FILL THIS OUT - LEE

##### **Design**
* FILL THIS OUT - ZAK This study would be a experimental design study. We step in and apply Vr-based therapy to one of the participant groups and not to the other hence experimental.

##### **Materials**
* FILL THIS OUT - ZAK The materials needed are the Participants, Vr Equipment and CBT method equipment. There are also some variables age, gender and GAD measurements. 

##### **Procedure**
* FILL THIS OUT - LEE
      
### 6 - **Results** (40M)
##### **Descriptive Statistics**
* FILL THIS OUT - ZAK

##### **Inferential Statistics**
* FILL THIS OUT - LEE

##### **Statistical Tests**
* FILL THIS OUT - ZAK

##### **Magnitude and Direction of Results**
* FILL THIS OUT - LEE
      
### 7 - **Discussion** (10M)
##### **Outline Findings and Relation To The Hypothesis**
* FILL THIS OUT - LEE

##### **Limitations (if confounding variables are clearly identified by your group)**
* FILL THIS OUT - ZAK
      
### 8 - **References** (2.5M)
* FILL THIS OUT - LEE/ZAK




